task_id: "local_runs"
run_id: "two_tower"
num_epochs: 1
dataset_dir: "datasets/docker_parquet"
commit_hash: "whatever"
batch_size: 64
learning_rate: 1e-2
reuse_epoch: True
dataloader_workers: 4
loss:
  type: triplet
  margin: 0.1
  batch_size: 64
  num_negatives: 63
negatives:
  type: batch
text_vectorizer:
  type: dictionary
  dictionary_path: datasets/docker/token_dictionary_150k_0k_0k
  word_unigrams_limit: 8
  word_bigrams_limit: 0
  char_trigrams_limit: 0
  num_oov_tokens: 2
model:
  type: TwoTower
  text_embedding:
    num_embeddings: 200000
    embedding_dim: 256
  fc_dim: 128
  output_dim: 128
recall_validation:
  enabled: True
  k:
    - 10
  query_typo_probabilities:
    0.0