task_id: "local_runs"
run_id: "multi_modal"
num_epochs: 1
dataset_dir: "datasets/docker_parquet"
commit_hash: "whatever"
batch_size: 64
learning_rate: 1e-2
reuse_epoch: True
dataloader_workers: 4
dataset:
  query_features:
    - name: "query_search_phrase"
      type: "text"
  product_features:
    - name: "product_name"
      type: "text"
    - name: "product_category_id"
      type: "categorical"
      dictionary_path: "datasets/docker_parquet/categories"
      num_oov_categories: 23
loss:
  type: triplet
  margin: 0.1
  batch_size: 64
  num_negatives: 63
negatives:
  type: batch
text_vectorizer:
  type: dictionary
  dictionary_path: datasets/docker/token_dictionary_150k_0k_0k
  word_unigrams_limit: 8
  word_bigrams_limit: 0
  char_trigrams_limit: 0
  num_oov_tokens: 50000
model:
  type: MultiModalTwoTower
  text_embedding:
    num_embeddings: 200000
    embedding_dim: 256
  category_feature:
    num_embeddings: 23000
    embedding_dim: 32
  fc_dim: 128
  output_dim: 128
  query:
    text_feature: "query_search_phrase"
  product:
    text_feature: "product_name"
    categorical_feature: "product_category_id"
validate_recall: False
