task_id: "new_loss"
run_id: "triplets"
num_epochs: 5
dataset_dir: "datasets/local"
commit_hash: "whatever"
batch_size: 64
learning_rate: 1e-2
reuse_epoch: True
dataloader_workers: 4
loss:
  type: batch_softmax
  batch_size: 64
negatives:
  type: batch
text_vectorizer:
  type: dictionary
  dictionary_path: datasets/local/dictionary_100k_46k_16k
  word_unigrams_limit: 8
  word_bigrams_limit: 7
  char_trigrams_limit: 35
  num_oov_tokens: 38000
model:
  type: SimpleTextEncoder
  text_embedding:
    num_embeddings: 200000
    embedding_dim: 256
  fc_dim: 128
  output_dim: 128
validate_recall: False
