task_id: "local_runs"
run_id: "text_128_cat_32_linear_256"
num_epochs: 2
dataset_dir: "datasets/local_parquet"
commit_hash: "whatever"
batch_size: 64
learning_rate: 1e-2
reuse_epoch: True
dataloader_workers: 4
dataset:
  query_features:
    - name: "query_search_phrase"
      type: "text"
  product_features:
    - name: "product_name"
      type: "text"
    - name: "product_category_id"
      type: "categorical"
      dictionary_path: "datasets/local_parquet/categories_dictionary_22975"
      num_oov_categories: 23
loss:
  type: batch_softmax
  batch_size: 64
  temperature: 0.1
negatives:
  type: batch
text_vectorizer:
  type: dictionary
  dictionary_path: datasets/local_parquet/token_dictionary_150000_0_0
  word_unigrams_limit: 8
  word_bigrams_limit: 0
  char_trigrams_limit: 0
  num_oov_tokens: 50000
model:
  type: MultiModalTwoTower
  text_embedding:
    num_embeddings: 200000
    embedding_dim: 256
  category_feature:
    num_embeddings: 23000
    embedding_dim: 32
  hidden_layers: []
  output_dim: 256
  query:
    text_feature: "query_search_phrase"
  product:
    text_feature: "product_name"
    categorical_feature: "product_category_id"
recall_validation:
  enabled: False
  k:
    - 10
    - 60
    - 100
    - 1024
  query_typo_probabilities:
    - 0.0
