task_id: "local_runs"
run_id: "triplet_loss_margin_01"
num_epochs: 2
dataset_dir: "datasets/local_parquet"
commit_hash: "whatever"
batch_size: 64
learning_rate: 1e-2
reuse_epoch: True
dataloader_workers: 4
dataset:
  query_features:
    - name: "query_search_phrase"
      type: "text"
  product_features:
    - name: "product_name"
      type: "text"
loss:
  type: triplet
  batch_size: 64
  num_negatives: 63
  margin: 0.1
negatives:
  type: batch
text_vectorizer:
  type: dictionary
  dictionary_path: datasets/local_parquet/token_dictionary_150000_0_0
  word_unigrams_limit: 10
  word_bigrams_limit: 0
  char_trigrams_limit: 0
  num_oov_tokens: 50000
model:
  type: TwoTower
  text_embedding:
    num_embeddings: 200000
    embedding_dim: 256
  hidden_layers:
    - 128
  last_linear: True
  output_dim: 128
  query:
    text_feature: "query_search_phrase"
  product:
    text_feature: "product_name"
recall_validation:
  enabled: False
  k:
    - 10
    - 60
    - 100
    - 1024
  query_typo_probabilities:
    - 0.0
